### ISSUE TITLE
Add a `western_equivalent` / `also_known_as` / `alias`  table

### ISSUE THREAD

**Issue by joereynolds** [joereynolds/raga-of-the-week#11]
This should give show other ways that this raga is known as.

For example, Kalyani is also known as lydian. Sankarabharanam as Ionian/major etc...

On top of this. We can create a command that will populate these after the fact.

For example app:link_akas will go through scales/modes and find ragas with those and populate them.

pseudocode
```
LinkAkas

formulas = [
    phrygian: 1 b2 b3 4 5 b6 b7,
    harmonic minor: 1 2 b3 4 5 b6 7
]

for raga in ragas:
    for formula in formulas:
        if formula == raga.formula:
            aka.insert(raga.id, formula_name)
```

This would be better maintained in `western_scales` table

### Todo

- [x] - Create a `western_scales` table
- [x] - Create a `also_known_as` table
- [x] - Create the above command

**Comment by joereynolds** [comment]
https://github.com/joereynolds/raga-of-the-week/commit/a5877c8762ec97748aa6545f8648689f7611e161
